version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocyclo
    - nolintlint
  settings:
    errcheck:
      check-type-assertions: true
    gocyclo:
      min-complexity: 10
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
  exclusions:
    presets: []

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
